// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Initialize the audio engine with the DeepFilter model
Future<void> initEngine({required List<int> modelData}) =>
    RustLib.instance.api.crateApiInitEngine(modelData: modelData);

/// Start recording audio to the specified file path
Future<void> startRecording({required String outputPath}) =>
    RustLib.instance.api.crateApiStartRecording(outputPath: outputPath);

/// Stop recording and save the file
Future<String> stopRecording() => RustLib.instance.api.crateApiStopRecording();

/// Play audio from the specified file path
Future<void> startPlayback({required String filePath}) =>
    RustLib.instance.api.crateApiStartPlayback(filePath: filePath);

/// Stop playback
Future<void> stopPlayback() => RustLib.instance.api.crateApiStopPlayback();

/// Get current recording/playback status
Future<RecordingStatus> getStatus() => RustLib.instance.api.crateApiGetStatus();

/// Check if playback has finished
Future<bool> isPlaybackFinished() =>
    RustLib.instance.api.crateApiIsPlaybackFinished();

/// Recording status for UI updates
class RecordingStatus {
  final bool isRecording;
  final bool isPlaying;
  final BigInt durationMs;
  final String? error;

  const RecordingStatus({
    required this.isRecording,
    required this.isPlaying,
    required this.durationMs,
    this.error,
  });

  @override
  int get hashCode =>
      isRecording.hashCode ^
      isPlaying.hashCode ^
      durationMs.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordingStatus &&
          runtimeType == other.runtimeType &&
          isRecording == other.isRecording &&
          isPlaying == other.isPlaying &&
          durationMs == other.durationMs &&
          error == other.error;
}
