// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Initialize the audio engine with the DeepFilter model
Future<void> initEngine({required List<int> modelData}) =>
    RustLib.instance.api.crateApiInitEngine(modelData: modelData);

/// Start recording audio to the specified file path
Future<void> startRecording({required String outputPath}) =>
    RustLib.instance.api.crateApiStartRecording(outputPath: outputPath);

/// Stop recording and save the file
Future<String> stopRecording() => RustLib.instance.api.crateApiStopRecording();

/// Play audio from the specified file path
Future<void> startPlayback({required String filePath}) =>
    RustLib.instance.api.crateApiStartPlayback(filePath: filePath);

/// Stop playback
Future<void> stopPlayback() => RustLib.instance.api.crateApiStopPlayback();

/// Get current recording/playback status
Future<RecordingStatus> getStatus() => RustLib.instance.api.crateApiGetStatus();

/// Check if playback has finished
Future<bool> isPlaybackFinished() =>
    RustLib.instance.api.crateApiIsPlaybackFinished();

/// Enable or disable stream A
Future<void> setStreamAEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiSetStreamAEnabled(enabled: enabled);

/// Enable or disable stream B
Future<void> setStreamBEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiSetStreamBEnabled(enabled: enabled);

/// Check if stream A is enabled
Future<bool> isStreamAEnabled() =>
    RustLib.instance.api.crateApiIsStreamAEnabled();

/// Check if stream B is enabled
Future<bool> isStreamBEnabled() =>
    RustLib.instance.api.crateApiIsStreamBEnabled();

/// Get current system metrics (CPU/GPU usage)
Future<SystemMetrics> getSystemMetrics() =>
    RustLib.instance.api.crateApiGetSystemMetrics();

/// System metrics for UI display
class SystemMetrics {
  final double cpuUsagePercent;
  final double gpuUsagePercent;
  final bool nnapiAvailable;

  const SystemMetrics({
    required this.cpuUsagePercent,
    required this.gpuUsagePercent,
    required this.nnapiAvailable,
  });

  @override
  int get hashCode =>
      cpuUsagePercent.hashCode ^
      gpuUsagePercent.hashCode ^
      nnapiAvailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SystemMetrics &&
          runtimeType == other.runtimeType &&
          cpuUsagePercent == other.cpuUsagePercent &&
          gpuUsagePercent == other.gpuUsagePercent &&
          nnapiAvailable == other.nnapiAvailable;
}

/// Recording status for UI updates
class RecordingStatus {
  final bool isRecording;
  final bool isPlaying;
  final BigInt durationMs;
  final bool streamAEnabled;
  final bool streamBEnabled;
  final String? error;

  const RecordingStatus({
    required this.isRecording,
    required this.isPlaying,
    required this.durationMs,
    required this.streamAEnabled,
    required this.streamBEnabled,
    this.error,
  });

  @override
  int get hashCode =>
      isRecording.hashCode ^
      isPlaying.hashCode ^
      durationMs.hashCode ^
      streamAEnabled.hashCode ^
      streamBEnabled.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordingStatus &&
          runtimeType == other.runtimeType &&
          isRecording == other.isRecording &&
          isPlaying == other.isPlaying &&
          durationMs == other.durationMs &&
          streamAEnabled == other.streamAEnabled &&
          streamBEnabled == other.streamBEnabled &&
          error == other.error;
}
