// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  RecordingStatus dco_decode_recording_status(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  RecordingStatus sse_decode_recording_status(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_encode_list_prim_u_8_loose(
    List<int> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
    String? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  int cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_recording_status(
    RecordingStatus apiObj,
    wire_cst_recording_status wireObj,
  ) {
    wireObj.is_recording = cst_encode_bool(apiObj.isRecording);
    wireObj.is_playing = cst_encode_bool(apiObj.isPlaying);
    wireObj.duration_ms = cst_encode_u_64(apiObj.durationMs);
    wireObj.stream_a_enabled = cst_encode_bool(apiObj.streamAEnabled);
    wireObj.stream_b_enabled = cst_encode_bool(apiObj.streamBEnabled);
    wireObj.error = cst_encode_opt_String(apiObj.error);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_recording_status(
    RecordingStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__get_status(int port_) {
    return _wire__crate__api__get_status(port_);
  }

  late final _wire__crate__api__get_statusPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_deepfilter_test_wire__crate__api__get_status',
      );
  late final _wire__crate__api__get_status = _wire__crate__api__get_statusPtr
      .asFunction<void Function(int)>();

  void wire__crate__api__get_system_metrics(int port_) {
    return _wire__crate__api__get_system_metrics(port_);
  }

  late final _wire__crate__api__get_system_metricsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_deepfilter_test_wire__crate__api__get_system_metrics',
      );
  late final _wire__crate__api__get_system_metrics =
      _wire__crate__api__get_system_metricsPtr.asFunction<void Function(int)>();

  void wire__crate__api__init_engine(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> model_data,
  ) {
    return _wire__crate__api__init_engine(port_, model_data);
  }

  late final _wire__crate__api__init_enginePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_deepfilter_test_wire__crate__api__init_engine');
  late final _wire__crate__api__init_engine = _wire__crate__api__init_enginePtr
      .asFunction<
        void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_loose>)
      >();

  void wire__crate__api__is_playback_finished(int port_) {
    return _wire__crate__api__is_playback_finished(port_);
  }

  late final _wire__crate__api__is_playback_finishedPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_deepfilter_test_wire__crate__api__is_playback_finished',
      );
  late final _wire__crate__api__is_playback_finished =
      _wire__crate__api__is_playback_finishedPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__start_playback(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_path,
  ) {
    return _wire__crate__api__start_playback(port_, file_path);
  }

  late final _wire__crate__api__start_playbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_deepfilter_test_wire__crate__api__start_playback');
  late final _wire__crate__api__start_playback =
      _wire__crate__api__start_playbackPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__start_recording(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> output_path,
  ) {
    return _wire__crate__api__start_recording(port_, output_path);
  }

  late final _wire__crate__api__start_recordingPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_deepfilter_test_wire__crate__api__start_recording');
  late final _wire__crate__api__start_recording =
      _wire__crate__api__start_recordingPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__stop_playback(int port_) {
    return _wire__crate__api__stop_playback(port_);
  }

  late final _wire__crate__api__stop_playbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_deepfilter_test_wire__crate__api__stop_playback',
      );
  late final _wire__crate__api__stop_playback =
      _wire__crate__api__stop_playbackPtr.asFunction<void Function(int)>();

  void wire__crate__api__stop_recording(int port_) {
    return _wire__crate__api__stop_recording(port_);
  }

  late final _wire__crate__api__stop_recordingPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_deepfilter_test_wire__crate__api__stop_recording',
      );
  late final _wire__crate__api__stop_recording =
      _wire__crate__api__stop_recordingPtr.asFunction<void Function(int)>();

  void wire__crate__api__set_stream_a_enabled(int port_, bool enabled) {
    return _wire__crate__api__set_stream_a_enabled(port_, enabled);
  }

  late final _wire__crate__api__set_stream_a_enabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Bool)>>(
        'frbgen_deepfilter_test_wire__crate__api__set_stream_a_enabled',
      );
  late final _wire__crate__api__set_stream_a_enabled =
      _wire__crate__api__set_stream_a_enabledPtr
          .asFunction<void Function(int, bool)>();

  void wire__crate__api__set_stream_b_enabled(int port_, bool enabled) {
    return _wire__crate__api__set_stream_b_enabled(port_, enabled);
  }

  late final _wire__crate__api__set_stream_b_enabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Bool)>>(
        'frbgen_deepfilter_test_wire__crate__api__set_stream_b_enabled',
      );
  late final _wire__crate__api__set_stream_b_enabled =
      _wire__crate__api__set_stream_b_enabledPtr
          .asFunction<void Function(int, bool)>();

  void wire__crate__api__is_stream_a_enabled(int port_) {
    return _wire__crate__api__is_stream_a_enabled(port_);
  }

  late final _wire__crate__api__is_stream_a_enabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_deepfilter_test_wire__crate__api__is_stream_a_enabled',
      );
  late final _wire__crate__api__is_stream_a_enabled =
      _wire__crate__api__is_stream_a_enabledPtr.asFunction<void Function(int)>();

  void wire__crate__api__is_stream_b_enabled(int port_) {
    return _wire__crate__api__is_stream_b_enabled(port_);
  }

  late final _wire__crate__api__is_stream_b_enabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_deepfilter_test_wire__crate__api__is_stream_b_enabled',
      );
  late final _wire__crate__api__is_stream_b_enabled =
      _wire__crate__api__is_stream_b_enabledPtr.asFunction<void Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_new_list_prim_u_8_loose(
    int len,
  ) {
    return _cst_new_list_prim_u_8_loose(len);
  }

  late final _cst_new_list_prim_u_8_loosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(ffi.Int32)
        >
      >('frbgen_deepfilter_test_cst_new_list_prim_u_8_loose');
  late final _cst_new_list_prim_u_8_loose = _cst_new_list_prim_u_8_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_deepfilter_test_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPostCObjectFnType =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)
      >
    >;
typedef DartPort = ffi.Int64;

final class wire_cst_list_prim_u_8_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_recording_status extends ffi.Struct {
  @ffi.Bool()
  external bool is_recording;

  @ffi.Bool()
  external bool is_playing;

  @ffi.Uint64()
  external int duration_ms;

  @ffi.Bool()
  external bool stream_a_enabled;

  @ffi.Bool()
  external bool stream_b_enabled;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> error;
}
